version: "2"

services:
  web:
    image: dorsaydevelopment/mountainhunter.ca
    links:
      - db:mysql
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=mtnhunter1
      - WORDPRESS_DB_NAME=mountainhunter
  db:
    image: mysql
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mtnhunter1
      - MYSQL_DATABASE=mountainhunter

volumes:
  mysql-db:
    driver: local